### ISSUE TITLE
Instruktionerna är fel

### ISSUE THREAD

**Issue by pzmn** [itggot/put_to_bed#1]
I README.md står det att return ska ge "Nighty Nighty, {namnet}!"
I testet står det att return ska ge "Nighty nighty, {namnet}!"
N ≠ n

**Comment by itggot-daniel-berg** [comment]
Ajaj! Om du är van github-användare får du gärna klona, fixa och göra en pull request :neckbeard:

**Comment by itggot-daniel-berg** [comment]
Det verkar som @davidITG har fixat missen.
